#pragma once

#include <stdint.h>

#ifndef PICO_ARC_FLASH_TOTAL_BYTES
#define PICO_ARC_FLASH_TOTAL_BYTES (16u * 1024u * 1024u)
#endif

#ifndef PICO_ARC_FLASH_STORAGE_BYTES
#define PICO_ARC_FLASH_STORAGE_BYTES (1u * 1024u * 1024u)
#endif

#ifndef PICO_ARC_FLASH_FIRMWARE_BYTES
#define PICO_ARC_FLASH_FIRMWARE_BYTES \
    (PICO_ARC_FLASH_TOTAL_BYTES - PICO_ARC_FLASH_STORAGE_BYTES)
#endif

#define PICO_ARC_FLASH_APP_CONFIG_OFFSET 0x00F00000u
#define PICO_ARC_FLASH_APP_CONFIG_SIZE 0x00010000u
#define PICO_ARC_FLASH_APP_STATE_B_OFFSET 0x00F10000u
#define PICO_ARC_FLASH_APP_STATE_B_SIZE 0x00010000u
#define PICO_ARC_FLASH_CAPTURE_LOG_OFFSET 0x00F20000u
#define PICO_ARC_FLASH_CAPTURE_LOG_SIZE 0x000E0000u

_Static_assert(PICO_ARC_FLASH_TOTAL_BYTES == 0x01000000u,
               "Pico-ARC452A21 expects a 16 MB flash device");
_Static_assert(PICO_ARC_FLASH_APP_CONFIG_OFFSET >= PICO_ARC_FLASH_FIRMWARE_BYTES,
               "app config partition must sit outside the firmware partition");
